[project]
name = "travel-reimburse"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "joblib>=1.5.1",
    "lightgbm>=4.6.0",
    "pandas>=2.3.0",
    "scikit-learn>=1.7.0",
]
